### PR TITLE
Simplifies async code by removing unnecessary 'async's

### PR DESCRIPTION
**Pull request by MihaMarkic**

### CODE REVIEW

**Comment by bradygmsft** [comment]
@MihaMarkic - thanks for the pull request. It seems to comprehensively remove a good number of async uses. Were these in your opinion extraneous or unnecessary? When I looked through the changes in the PR I didn't see any immediate concerns, like making previously-async code that wraps sensitive async code in a newly-converted-to-sync method. It absolutely makes the code easier to read and understand. I presume you've tested the results of the changes and things are stable? 

This looks a lot better. 

BTW, are you an NTK attendee? It is a great conference, year after year.

**Comment by MihaMarkic** [comment]
Hi @bradygmsft 

The thing with async keyword is that it generates code in the background which induces unnecessary code and a tiny app and compiler performance hit. So it is better to avoid it if not really needed.
And no, I didn't test much of the changes as they look pretty straightforward to me (no functionality change).
And yes, I plan to attend the NTK as every year. It'd be a sin to miss that beautiful venue :)

**Comment by bradygmsft** [comment]
@MihaMarkic agreed with you on NTK. I had dinner with Bojan the other night when he was in town - planning on attending this year so I hope to see you there. 

Agreed this doesn't look like it'd cause any functionality. Let me and my team grab your changes and try them out, then we'll validate and make sure things aren't awry. Once we do that we'll merge. Just want to make sure we're not breaking anything.

**Comment by jsuarezruiz** [comment]
Looks nice for me. Tested.

**Comment by MihaMarkic** [comment]
@bradygmsft Likewise, will be nice to you.

**Comment by bradygmsft** [comment]
@MihaMarkic indeed! I'll make sure @bojanv lets you know our plans if I can make it!

**Pull request merged**
