### PR TITLE
Migrate to PackageReference

### PR DESCRIPTION
**Pull request by kzu**

### CODE REVIEW

**Comment by kzu** [comment]
@eiximenis This significantly speeds up restore operations in VS and causes far less UI delays on solution open and build.

**Comment by jsuarezruiz** [comment]
Nice @kzu!

**Comment by kzu** [comment]
@glennwester is anyone looking at PRs and merging them?

**Comment by bradygmsft** [comment]
Yes @glennwester we are indeed reviewing them. Apologies for the delay. @dasanagu and I are trying to triage all of these but we have a few other work streams going on at the moment too. We'll look into it.

**Pull request merged**
